[package]
name = "asterisk-ami"
description = "Minimalistic library to communicate with an Asterisk server using the AMI over TCP protocol"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1.5.4"
lazy_static = "1.4.0"